apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: config-service
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: config-service
    spec:
      containers:
        - env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULTLABEL
              value: master
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME
              value:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
              value:
          image:
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8888/actuator/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: config-service
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}
