apiVersion: v1
kind: Service
metadata:
  name: distillehr-document-storage-service-nodeport
spec:
  type: NodePort
  selector:
    io.kompose.service: distillehr-document-storage-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31102