apiVersion: v1
kind: Service
metadata:
  name: distillehr-medhost-enterprise-extraction-service-db-nodeport
spec:
  type: NodePort
  selector:
    io.kompose.service: distillehr-medhost-enterprise-extraction-service-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 31101