apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: distillehr-document-viewer-service
  name: distillehr-document-viewer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: distillehr-document-viewer-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: distillehr-document-viewer-service
    spec:
      containers:
        - env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_PROFILES_ACTIVE
              value: config-client,docker1
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
          image:
          name: distillehr-document-viewer-service
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
