apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: distillehr-document-storage-service-db
  name: distillehr-document-storage-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: distillehr-document-storage-service-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: distillehr-document-storage-service-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: distillehr-document-storage-service-db
            - name: POSTGRES_PASSWORD
              value: foobar11
            - name: POSTGRES_USER
              value: distillehr
          image: postgres:12.2
          name: distillehr-document-storage-service-db
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
