apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: distillehr-document-storage-service
  name: distillehr-document-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: distillehr-document-storage-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: distillehr-document-storage-service
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8888
            - name: SPRING_PROFILES_ACTIVE
              value: config-client,docker1
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
          image:
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8081/actuator/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: distillehr-document-storage-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
