apiVersion: v1
kind: Service
metadata:
  name: distillehr-medhost-enterprise-extraction-service-nodeport
spec:
  type: NodePort
  selector:
    io.kompose.service: distillehr-medhost-enterprise-extraction-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31100